[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"

[build.processing]
  skip_processing = true

[build.lifecycle]
  postinstall = "npm install --legacy-peer-deps"
